import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from '@/components/navbar';
import ThemeContextProvider from '@/context/theme-context';
import './globals.css';

const nunito = Nunito({
  weight: ['300', '600', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Countries Flags',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${nunito.className} bg-slate-100 dark:bg-slate-900`}>
        <ThemeContextProvider>
          <Navbar />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
